----------------------- tASK_01 ------------------------------
USE UNIVER;
SELECT FACULTY.FACULTY,PROFESSION,SUBJECT, AVG(NOTE) AS [средний балл]
from FACULTY join GROUPS G on FACULTY.FACULTY = G.FACULTY and G.FACULTY = 'ИТ'
join STUDENT S on G.IDGROUP = S.IDGROUP
join PROGRESS P on S.IDSTUDENT = P.IDSTUDENT
group by rollup (FACULTY.FACULTY,PROFESSION,SUBJECT)
----------------------- tASK_02 ------------------------------
USE UNIVER;
SELECT FACULTY.FACULTY,PROFESSION,SUBJECT, AVG(NOTE) AS [средний балл]
from FACULTY join GROUPS G on FACULTY.FACULTY = G.FACULTY and G.FACULTY = 'ИТ'
join STUDENT S on G.IDGROUP = S.IDGROUP
join PROGRESS P on S.IDSTUDENT = P.IDSTUDENT
group by cube (FACULTY.FACULTY,PROFESSION,SUBJECT)
----------------------- tASK_03 ------------------------------
USE UNIVER;
select GROUPS.PROFESSION,P.SUBJECT,AVG(NOTE) as AVERAGE_NOTE
from GROUPS join STUDENT S on GROUPS.IDGROUP = S.IDGROUP and GROUPS.FACULTY='ИТ'
join PROGRESS P on S.IDSTUDENT = P.IDSTUDENT
group by P.SUBJECT, GROUPS.PROFESSION
UNION
select GROUPS.PROFESSION,P.SUBJECT,AVG(NOTE) as AVERAGE_NOTE
from GROUPS join STUDENT S on GROUPS.IDGROUP = S.IDGROUP and GROUPS.FACULTY='ХТиТ'
join PROGRESS P on S.IDSTUDENT = P.IDSTUDENT
group by P.SUBJECT, GROUPS.PROFESSION

USE UNIVER;
select GROUPS.PROFESSION,P.SUBJECT,AVG(NOTE) as AVERAGE_NOTE
from GROUPS join STUDENT S on GROUPS.IDGROUP = S.IDGROUP and GROUPS.FACULTY='ИТ'
join PROGRESS P on S.IDSTUDENT = P.IDSTUDENT
group by P.SUBJECT, GROUPS.PROFESSION
UNION ALL
select GROUPS.PROFESSION,P.SUBJECT,AVG(NOTE) as AVERAGE_NOTE
from GROUPS join STUDENT S on GROUPS.IDGROUP = S.IDGROUP and GROUPS.FACULTY='ХТиТ'
join PROGRESS P on S.IDSTUDENT = P.IDSTUDENT
group by P.SUBJECT, GROUPS.PROFESSION
----------------------- tASK_04 ------------------------------
USE UNIVER;
select GROUPS.PROFESSION,P.SUBJECT,AVG(NOTE) as AVERAGE_NOTE
from GROUPS join STUDENT S on GROUPS.IDGROUP = S.IDGROUP and GROUPS.FACULTY='ИТ'
join PROGRESS P on S.IDSTUDENT = P.IDSTUDENT
group by P.SUBJECT, GROUPS.PROFESSION
INTERSECT
select GROUPS.PROFESSION,P.SUBJECT,AVG(NOTE) as AVERAGE_NOTE
from GROUPS join STUDENT S on GROUPS.IDGROUP = S.IDGROUP and GROUPS.FACULTY='ХТиТ'
join PROGRESS P on S.IDSTUDENT = P.IDSTUDENT
group by P.SUBJECT, GROUPS.PROFESSION
----------------------- tASK_05 ------------------------------
USE UNIVER;
select GROUPS.PROFESSION,P.SUBJECT,AVG(NOTE) as AVERAGE_NOTE
from GROUPS join STUDENT S on GROUPS.IDGROUP = S.IDGROUP and GROUPS.FACULTY='ИТ'
join PROGRESS P on S.IDSTUDENT = P.IDSTUDENT
group by P.SUBJECT, GROUPS.PROFESSION
EXCEPT
select GROUPS.PROFESSION,P.SUBJECT,AVG(NOTE) as AVERAGE_NOTE
from GROUPS join STUDENT S on GROUPS.IDGROUP = S.IDGROUP and GROUPS.FACULTY='ХТиТ'
join PROGRESS P on S.IDSTUDENT = P.IDSTUDENT
group by P.SUBJECT, GROUPS.PROFESSION
----------------------- tASK_06 ------------------------------
-------------- EXAMPLE 1 ------------------
USE Ilya_MyBase;
SELECT
Водитель,
COUNT(*)[Количество поездок]
FROM Грузоперевозки
GROUP BY rollup (Водитель)
-------------- EXAMPLE 2 ------------------
USE Ilya_MyBase;
SELECT 
Стаж,
COUNT(*)[Количество поездок]
FROM Грузоперевозки 
INNER JOIN Водители ON Грузоперевозки.Водитель = Водители.ID_водителя
INNER JOIN Маршруты ON Маршруты.ID_маршрута = Грузоперевозки.Маршрут
GROUP BY cube (Стаж )