-- TASK_01 --
USE  UNIVER;
SELECT AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	FROM AUDITORIUM_TYPE INNER JOIN AUDITORIUM
	ON AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE

-- TASK_02 --
USE  UNIVER;
SELECT AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	FROM AUDITORIUM_TYPE INNER JOIN AUDITORIUM
	ON AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE
	AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%'

-- TASK_03 --
USE UNIVER;
select STUDENT.NAME,
       FACULTY.FACULTY,
       PULPIT.PULPIT,
       PROFESSION.PROFESSION_NAME,
       SUBJECT.SUBJECT_NAME,
       case
           when (PROGRESS.NOTE = 6) then 'шесть'
           when (PROGRESS.NOTE = 7) then 'семь'
           when (PROGRESS.NOTE = 8) then 'восемь'
           end [Oценка]
from PROGRESS
          inner join STUDENT on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
          inner join SUBJECT on SUBJECT.SUBJECT = PROGRESS.SUBJECT
          inner join GROUPS on GROUPS.IDGROUP = STUDENT.IDGROUP
          inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
          inner join PULPIT on PULPIT.PULPIT = SUBJECT.PULPIT
          inner join FACULTY on FACULTY.FACULTY = PULPIT.FACULTY
where PROGRESS.NOTE between 6 and 8
order by FACULTY.FACULTY

-- TASK_04 --
USE UNIVER;

SELECT  PULPIT.PULPIT_NAME, ISNULL(TEACHER.TEACHER_NAME,'***')[TEACHER_NAME]
	FROM PULPIT LEFT OUTER JOIN TEACHER
	ON PULPIT.PULPIT =TEACHER.PULPIT

-- TASK_05 --
USE UNIVER;

SELECT STUDENT.NAME, PROGRESS.NOTE FROM 
	STUDENT FULL OUTER JOIN PROGRESS
	ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT

SELECT PROGRESS.NOTE, STUDENT.NAME FROM 
	PROGRESS FULL OUTER JOIN STUDENT
	ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	WHERE PROGRESS.NOTE IS NULL

SELECT PROGRESS.NOTE, STUDENT.NAME FROM 
	PROGRESS FULL OUTER JOIN STUDENT
	ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	WHERE PROGRESS.NOTE IS NOT NULL

-- TASK_06 --
USE UNIVER;

SELECT AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	FROM AUDITORIUM CROSS JOIN AUDITORIUM_TYPE
	WHERE AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE

-- TASK_07 --
USE Ilya_MyBase;

SELECT Наименование_маршрута, Дальность, Имя, Фамилия, Стаж, Оплата,
case
           when (Стаж >= 4) then 'Не переживай'
           when (Стаж < 4) then 'Всегда есть шанс'
		   else 'Посмотрим'
           end [Вероятнсть успеха]
FROM Грузоперевозки
	INNER JOIN Маршруты
	ON Грузоперевозки.Маршрут = Маршруты.ID_маршрута
	INNER JOIN Водители
	ON Грузоперевозки.Водитель = Водители.ID_водителя
	WHERE Стаж between 1 and 5
